import type { Metadata } from "next";
import { Fredoka } from "next/font/google";
import "./globals.css";
import "remixicon/fonts/remixicon.css";

const fredoka = Fredoka({
  subsets: ["latin"],
  weight: ["400", "500", "700"],
  variable: "--font-fredoka",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${fredoka.variable} font-sans`}>{children}</body>
    </html>
  );
}
